export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const FETCH_NOTE_DETAILS = 'FETCH_NOTE_DETAILS';
export const DELETE_NOTE = 'DELETE_NOTE';